version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Restore solution
          command: dotnet restore
      - run:
          name: Build solution
          command: dotnet build
      
#      - run:
#          name: Run tests 
#          command: dotnet test --no-build --logger "trx;LogFileName=../../../xunit-output.xml" src/Seedwork.Test

      # Convert xUnit output to JUnit output, as described at
      # http://geeks.akinox.com/2017/03/17/migrating-dotnetcore/#dotnet-test-and-shippable
#      - run:
#          name: Process test results
#          command: |
#            apt-get update
#            apt-get -y install xsltproc
#            xsltproc -o shippable/testresults/result.xml scripts/trx-to-junit.xslt xunit-output.xml
#            rm xunit-output.xml
    
#      - store_test_results:
#          path: "shippable/testresults/"